accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth import login, logout
#from django.conf import settings
app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    #url(r'^login/$' , login , {'template_name':'login.html'}, name='login')
    url(r'^login/$',LoginView.as_view(template_name='login.html'), name='login'),
    #url(r'^logout/$' , logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'signup$' , views.register, name='register'),
    url(r'^(?P<slug>[-\w]+)/$', views.profile, name='profile'),
]

notes/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes_app.urls', namespace='notes')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notes_app/urls.py
from django.conf.urls import url
from . import views


app_name = 'note_app'

urlpatterns = [
    url(r'^$', views.all_notes, name='all_notes'),
    #url(r'^(?P<id>\d+)$', views.detail, name='note_detail'),
    url(r'^(?P<slug>[-\w]+)/$', views.detail, name='note_detail'),
    url(r'^add$', views.note_add, name='add_note'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.note_edit, name='note_edit'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from django.db.models.signals import post_save
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #first_name = models.CharField(blank=True, max_length=100)
    #last_name = models.CharField(blank=True, max_length=100)
    slug = models.SlugField(null=True)
    headline = models.CharField(blank=True, max_length=100)
    bio = models.TextField(blank=True)
    join_date = models.DateTimeField(blank=True, default=datetime.datetime.now)

    def save(self , *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user)
        super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return '%s' %(self.user)

### Signals

def create_profile(sender , **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

notes_app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify

# Create your models here.
class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    slug = models.SlugField(null = True, blank=True)
    content = models.TextField(blank=True)
    created = models.DateTimeField(blank=True, default=datetime.datetime.now)
    active = models.BooleanField(default=True)
    tags = models.CharField(blank=True, max_length=100)


    def save(self , *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Note, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

notes_app/forms.py
from django import forms
from .models import Note
class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'content', 'tags']

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login , authenticate
from .models import Profile
# Create your views here.

def home(request):
    pass


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')

            user = authenticate(username=username , password=password)
            login(request, user)
            print(request.user)
            return redirect('/notes')
    else:
        form = UserCreationForm

    context = {
        'form' : form ,
    }
    return render(request, 'signup.html', context)

def profile(request, slug):
    profile = Profile.objects.get(slug=slug)
    context = {
        'profile' : profile ,
    }
    return render(request , 'profile.html' , context)

notes_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
# Create your views here.
from .models import Note
from .forms import NoteForm

## show all available notes
def all_notes(request):
    #html = "<html> <body> <h1>Welcome In Django with Hasan Alkaf </h1> </body> </html>"
    #return HttpResponse(html)
    #render(request, '<h1>Welcome In Django with Hasan Alkaf </h1>', {})
    all_notes = Note.objects.all()

    context ={
        'all_notes' : all_notes
    }

    return render(request, 'notes.html', context)

## show one note
def detail(request, slug):
    note = Note.objects.get(slug=slug)
    context = {
    'note' : note
    }
    return render(request, 'one_note.html' , context)

## add note
def note_add(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            return redirect('/notes')
    else:
        form = NoteForm()

    context = {
        'form' : form
    }
    return render(request, 'add.html', context)

def note_edit(request, slug):
    note = get_object_or_404(Note, slug=slug)
    print(note)
    if request.method == 'POST':
        form = NoteForm(request.POST, instance = note)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            return redirect('/notes')
    else:
        form = NoteForm(instance = note)

    context = {
        'form' : form
    }
    return render(request, 'create.html', context)

accounts/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block body %}

<div class="row">
<div style="margin-top:60px; margin-left:100px; height:520px;">
<form method="post">
  {% csrf_token %}
  {{form}}
  <button type="submit" class="btn btn-primary"> Login </button>
</form>

</div>
</div>
{% endblock %}

<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


{% comment %}
<div class="container">
    <div class="row-fluid">
        <div class="span12">
            <div class="span6">
                <div class="area">
                    <form class="form-horizontal">
                        <div class="heading">
                            <h4 class="form-heading">Sign In</h4>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputUsername">Username</label>

                            <div class="controls">
                                <input id="inputUsername" placeholder=
                                "E.g. ashwinhegde" type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputPassword">Password</label>

                            <div class="controls">
                                <input id="inputPassword" placeholder=
                                "Min. 8 Characters" type="password">
                            </div>
                        </div>

                        <div class="control-group">
                            <div class="controls">
                                <button class="btn btn-success" type=
                                "submit">Sign In</button>
                            </div>
                        </div>

                        <div class="alert alert-error">
                          Do not have account ..<a href="#">sign up</a> now
                        </div>
                    </form>
                </div>
            </div>


            </div>
        </div>
    </div>
</div>
{% endcomment %}

accounts/templates/signup.html
{% extends "base.html" %}
{% load static %}
{% block body %}

<div class="row">
  <div style="margin-top:60px; margin-left:100px; height:520px;">
<form method="post">
  {% csrf_token %}
  {{form}}
  <button type="submit" class="btn btn-primary"> Sign Up </button>
</form>
</div>
</div>
{% endblock %}


{% comment %}
<div class="span6">
                <div class="area">
                    <form class="form-horizontal">
                        <div class="heading">
                            <h4 class="form-heading">Sign Up</h4>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="inputFirst">First
                            Name</label>

                            <div class="controls">
                                <input id="inputFirst" placeholder=
                                "E.g. Ashwin" type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for="inputLast">Last
                            Name</label>

                            <div class="controls">
                                <input id="inputLast" placeholder="E.g. Hegde"
                                type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputEmail">Email</label>

                            <div class="controls">
                                <input id="inputEmail" placeholder=
                                "E.g. ashwinh@cybage.com" type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputUser">Username</label>

                            <div class="controls">
                                <input id="inputUser" placeholder=
                                "E.g. ashwinhegde" type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputPassword">Password</label>

                            <div class="controls">
                                <input id="inputPassword" placeholder=
                                "Min. 8 Characters" type="password">
                            </div>
                        </div>

                        <div class="control-group">
                            <div class="controls">
                                <button class=
                                "btn btn-success" type="submit">Sign
                                Up</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
{% endcomment %}

notes_app/templates/add.html
{% extends "base.html" %}
{% block body %}

<div class="row">
  <div class="add_form">
    <form method="post">
      {% csrf_token %}
      {{form}}
      <button type="submit" class="btn btn-primary">Add Note</button>
    </form>
  </div>
</div>
{% endblock %}

notes_app/templates/all_notes.html
<html>
  <body>
    <h1>  All the available Notes </h1>

    <a href="{% url 'notes:add_note' %}">Add New Note</a>
    <br>
    <hr>
      {% for note in all_notes %}
      <a href="{% url 'notes:note_detail' note.slug %}">{{note}}</a>


      </br>
      {% endfor %}
  </body>
</html>

notes_app/templates/create.html
{% extends "base.html" %}
{% block body %}


<form method="post">
  {% csrf_token %}
  {{form}}
  <button type="submit" class="btn btn-primary">Update Note</button>
</form>


{% endblock %}

notes_app/templates/note_detail.html
<h2>  {{note}} </h2>
<hr>
<a href="{% url 'notes:note_edit' note.slug %}">Update Note Details</a>
<hr>
<br>
<h3> {{note.title}} </h3>
<h3> {{note.slug}} </h3>
<h3> {{note.created}} </h3>
<h3> {{note.active}} </h3>
<h3> {{note.tags}} </h3>

notes_app/templates/notes.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <!-- Start blog Area -->
    <section class="blog-area section-gap">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 pb-30 header-text">
            <h1>Our Recent Notes</h1>
            <p>
              Create, Update, And Share Your Notes With Others <br> Developed By Hasan Alkaf.
            </p>
          </div>
        </div>
        <div class="row">

          {% for note in all_notes %}

          <div class="single-blog col-lg-4 col-md-4">

            <img class="f-img img-fluid mx-auto" src="{% static 'home-static/img/b1.jpg' %}" alt="">

            <h4>
              <a href="{% url 'notes:note_detail' note.slug %}">{{note.title}}</a>
            </h4>
            <p>
              {{note.content}}	</p>
            <div class="bottom d-flex justify-content-between align-items-center flex-wrap">
              <div>
                <img class="img-fluid" src="{% static 'home-static/img/user.png' %}" alt="">
                <a href="#"><span>{{note.user.username}}</span></a>
              </div>
              <div class="meta">
                {{note.created|date:"j M"}}
              </div>
            </div>
          </div>

          {% endfor %}

        </div>
      </div>
    </section>
    <!-- end blog Area -->
{% endblock %}

notes_app/templates/one_note.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <!-- Start blog Area -->
    <section class="blog-area section-gap">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 pb-30 header-text">
            <h1>{{note}}</h1>
            <p>
              {{note.created|date:"j M"}} | {{note.tags}} |{{note.user.username}}
            </p>
          </div>
        </div>
        <div class="row">
          <div class="single-blog col-lg-10 col-md-10">

            <p>
              {{note.content}}							</p>
            <div class="bottom d-flex justify-content-between align-items-center flex-wrap">
              <div>
                <img class="img-fluid" src="{% static 'home-static/img/user.png' %}" alt="">
                <a href="#"><span>{{note.user.username}}</span></a>
              </div>
              <div class="meta">
                {{note.created|date:"j M"}}
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>
    <!-- end blog Area -->

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
  <!-- Mobile Specific Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Favicon-->
  <link rel="shortcut icon" href="img/fav.png">
  <!-- Author Meta -->
  <meta name="author" content="Colorlib">
  <!-- Meta Description -->
  <meta name="description" content="">
  <!-- Meta Keyword -->
  <meta name="keywords" content="">
  <!-- meta character set -->
  <meta charset="UTF-8">
  <!-- Site Title -->
  <title>Quick Notes</title>

  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    {% load static %}

    <link rel="stylesheet" href="{% static 'home-static/css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'home-static/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'home-static/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'home-static/css/nice-select.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'home-static/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'home-static/css/main.css' %}">
  </head>
  <body>

    <!-- Start Header Area -->
    <header class="default-header">
      <div class="container">
        <div class="header-wrap">
          <div class="header-top d-flex justify-content-between align-items-center">
            <div class="logo">
              <a href="#home"><img src="{% static 'home-static/img/logo2.png' %}" width="45" alt=""></a>
            </div>
            <div class="main-menubar d-flex align-items-center">
              <nav class="hide">
                <a href="#home">Home</a>
                <a href="#">Notes</a>
                <a href="#">Login</a>
                <a href="#">Signup</a>
              </nav>
              <div class="menu-bar"><span class="lnr lnr-menu"></span></div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- End Header Area -->

    <!-- Start blog Area -->
    {%  block body %}

    {% endblock %}
    <!-- end blog Area -->

    <!-- start footer Area -->
    <footer class="footer-area section-gap">
      <div class="container">
        <div class="row">
          <div class="col-lg-4  col-md-6">
            <div class="single-footer-widget mail-chimp">
              <h6 class="mb-20">Contact Us</h6>
              <p>
                56/8, bir uttam qazi nuruzzaman road, west panthapath, kalabagan, Dhanmondi, Dhaka - 1205
              </p>
              <h3>012-6532-568-9746</h3>
              <h3>012-6532-568-97468</h3>
            </div>
          </div>
          <div class="col-lg-6  col-md-12">
            <div class="single-footer-widget newsletter">
              <h6>Newsletter</h6>
              <p>You can trust us. we only send promo offers, not a single spam.</p>
              <div id="mc_embed_signup">
                <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">

                  <div class="form-group row" style="width: 100%">
                    <div class="col-lg-8 col-md-12">
                      <input name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
                      <div style="position: absolute; left: -5000px;">
                        <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                      </div>
                    </div>

                    <div class="col-lg-4 col-md-12">
                      <button class="nw-btn primary-btn">Subscribe<span class="lnr lnr-arrow-right"></span></button>
                    </div>
                  </div>
                  <div class="info"></div>
                </form>
              </div>
            </div>
          </div>
        </div>

        <div class="row footer-bottom d-flex justify-content-between">
          <p class="col-lg-8 col-sm-12 footer-text m-0">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
          <div class="col-lg-4 col-sm-12 footer-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
          </div>
        </div>
      </div>
    </footer>
    <!-- End footer Area -->

    <script src="{% static 'home-static/js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="{% static 'home-static/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.sticky.js' %}"></script>
    <script src="{% static 'home-static/js/parallax.min.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'home-static/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'home-static/js/waypoints.min.js' %}"></script>
    <script src="{% static 'home-static/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'home-static/js/main.js' %}"></script>
  </body>
</html>